`tbl_svysummary(include=)` updates to include more of the design columns
ddsjoberg/gtsummary pull request #1171
Opened 2022-03-09 01:02 UTC by ddsjoberg

@larmarange are you able to review this?

**What changes are proposed in this pull request?**

* No longer removing the strata column from survey objects from the columns that will be summarized in `tbl_svysummary()`. If users previously didn't indicate which variables to summarize with `include=`, then the strata column (if present) will now appear in the summary table. When using a srvyr class object, all columns will be printed in summary table by default. (#1166)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #1166

cc @aspina7

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

2022-03-09 08:27 UTC, larmarange requested changes
Hi @ddsjoberg 

Thanks a lot for the PR. I have the feeling that we should be simpler and treat equally `survey` and `srvyr` data sets.

2022-03-09 08:27 UTC, larmarange commented on NEWS.md
> +* No longer removing the strata column from survey objects from the columns that will be summarized in `tbl_svysummary()`. If users previously didn't indicate which variables to summarize with `inclu
Here the result will be different for a `survey` or a `srvyr` object. I would say that this is a complexity which is not relevant. The results should not change according to the type of the data set and both should be treated equally. I suspect that we will have misunderstanding if the rule differ for `survey` and `srvyr`.

I would be in favor in having a simple rule: all variables are, by default, returned by `everything()`. If user what a subset, they can use `include=` or `survey::subset()` or `srvyr::select()`.

In such case, we should simple remove `.remove_survey_cols()`

2022-03-09 08:27 UTC, larmarange commented on R/tbl_svysummary.R
> -        all.vars(x$call$strata),
cf. #1171 discussion. There are cases where we want to display `x$call$id`.
And in some (less frequent cases) we need to display statistics about `weights`. 

cf. previous comment. `everything()` should display all variables.

If really there is a need for identifying survey variables, let's create a `survey_vars()` selector and let the user indicates `include = -survey_vars()`

2022-03-09 15:57 UTC, ddsjoberg commented
thanks @larmarange , I updated to just print them all!

2022-03-10 14:33 UTC, larmarange approved these changes
Thanks a lot!! Thta's great

2022-03-10 16:17 UTC, merged

2022-03-10 18:54 UTC, aspina7 commented
Amazing thanks for moving so fast on this!