Further updates to `tbl_hierarchical()`
ddsjoberg/gtsummary pull request #2061
Opened 2024-11-08 22:46 UTC by ddsjoberg

**What changes are proposed in this pull request?**
<< Insert text here that can be directly copied into NEWS.md by your reviewer. >>

**If there is an GitHub issue associated with this pull request, please provide link.**

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from main branch.
- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

2024-11-08 22:48 UTC, ddsjoberg commented on R/brdg_hierarchical.R
> -          .data$variable == "..ard_hierarchical_overall..", label[["overall"]], .data$variable_level
FYI I think it'll be easier in the long run to retain the name from the ARD output, and the name overall may be too common and cause some name conflicts in the future

2024-11-08 22:49 UTC, ddsjoberg commented on R/tbl_hierarchical.R
> -                             id = NULL,
FYI I removed the default values for arguments that are required for the users to pass.

2024-11-11 19:39 UTC, edelarua requested changes
A few small suggestions but otherwise all good!! :)

2024-11-11 21:28 UTC, ddsjoberg commented on R/brdg_hierarchical.R
> +        variable = ifelse(.data$variable == "..ard_hierarchical_overall..", "..ard_hierarchical_overall..", .data$variable)
haha, thanks!

2024-11-11 22:42 UTC, merged