Add S3 methods for sorting & filtering hierarchical tables
ddsjoberg/gtsummary pull request #2097
Opened 2024-12-09 21:00 UTC by edelarua

**What changes are proposed in this pull request?**
- Added S3 methods `tbl_sort.tbl_hierarchical()` and `tbl_filter.tbl_hierarchical()` to sort and filter hierarchical tables.

Closes #2096 

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from main branch.
- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

2024-12-23 18:17 UTC, ddsjoberg commented
This is awesome @edelarua ! Thank you!!

When we're back from the holidays, let's chat about the user API. Maybe we can make it easier to implement from their end with respect to specifying the expression for filtering, for example. For example, would it be easier for them to specify the filter like `p >= 0.05` instead of `t = 0.05, .stat = "p"`?

2025-01-06 18:37 UTC, ddsjoberg commented
This is on hold until we see exactly how this will be implemented in `cards` (in case we can piggy back on that solution) https://github.com/insightsengineering/cards/issues/301

2025-04-10 18:44 UTC, ddsjoberg requested changes
Thank you sooooo much! We're very close here. Just a couple of comments and we'll be good to merge!

2025-04-10 18:44 UTC, ddsjoberg commented on NAMESPACE
> +export(tbl_filter)
We reserve the `tbl_*()` prefix for generating new tables.

Let's name the functions `filter_hierarchical` and `sort_hierarchical()`. Let's just make them functions instead of generics.

2025-04-10 18:44 UTC, ddsjoberg commented on R/tbl_filter.R
> +#' Some examples of possible filters:
Can you add a description of each of these filter explaining them like we did in the cards function?

2025-04-10 18:44 UTC, ddsjoberg commented on R/tbl_filter.R
> +#' # Example 1 - Row Sums > 3 -------------------
Can you add an explanation for in a comment what this filtering does?

2025-04-10 18:44 UTC, ddsjoberg commented on R/tbl_filter.R
> +#' # Example 2 - Row Sums <= 3 ------------------
Can we illustrate another filtering method here?

2025-04-10 23:29 UTC, edelarua commented on R/tbl_filter.R
> +#' # Example 2 - Row Sums <= 3 ------------------
Done!

2025-04-10 23:29 UTC, edelarua commented on R/tbl_filter.R
> +#' # Example 1 - Row Sums > 3 -------------------
Done!

2025-04-10 23:29 UTC, edelarua commented on R/tbl_filter.R
> +#' Some examples of possible filters:
Done!

2025-04-10 23:29 UTC, edelarua commented on NAMESPACE
> +export(tbl_filter)
Done!

2025-04-10 23:30 UTC, edelarua commented on DESCRIPTION
> +    person("Emily", "de la Rua", , role = "aut",
Done!

2025-04-11 00:24 UTC, ddsjoberg approved these changes
Amazing! Thank you so much for this great addition, and thank you for the revisions and patience! 🙇🏼‍♂️

2025-04-11 07:59 UTC, edelarua commented
@ddsjoberg sorry, I just pushed one last update. I noticed one special case (ordered factor variables) needs to re-sort the hierarchical ARD since it merges two together via `cards::bind_ard()` within the `tbl_hierarchical()` function, otherwise the final table sorting/filtering is messed up. 

Not sure if you want to do a quick re-review of the update (https://github.com/ddsjoberg/gtsummary/pull/2097/commits/42d32a9164c1f25c7023838bba4f6cdf99b3585b) before merging, but otherwise all good to go on my end - I updated the NEWS already.

2025-04-11 14:08 UTC, ddsjoberg commented
> @ddsjoberg sorry, I just pushed one last update. I noticed one special case (ordered factor variables) needs to re-sort and filter the hierarchical ARD since it merges two together and keeps all rows via `cards::bind_ard()` within the `tbl_hierarchical()` function, otherwise the final table sorting/filtering is messed up and empty rows are kept.
> 
> Not sure if you want to do a quick re-review of the update ([42d32a9](https://github.com/ddsjoberg/gtsummary/commit/42d32a9164c1f25c7023838bba4f6cdf99b3585b) and [5ef1571](https://github.com/ddsjoberg/gtsummary/commit/5ef157188e2a3b7690bf18d5ea68f37bed3c769d)) before merging, but otherwise all good to go on my end - I updated the NEWS already.

If you wrote a unit test for this case, go ahead and just merge. If not, can you add a unit test then merge? Thank you!!

2025-04-11 16:23 UTC, merged